# Generated by Django 3.1.2 on 2020-11-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('phone', models.CharField(max_length=11, verbose_name='Telefone celular')),
                ('address', models.CharField(max_length=100, verbose_name='Endereço')),
                ('complement', models.CharField(blank=True, max_length=50, null=True, verbose_name='Complemento')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users_images', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['name'],
            },
        ),
    ]
