# Generated by Django 3.1.2 on 2020-11-01 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pescaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_species', models.CharField(max_length=30, verbose_name='Espécie do peixe')),
                ('fish_weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Massa em kg')),
                ('image', models.ImageField(upload_to='fish_images', verbose_name='Foto do peixe')),
                ('fisherman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pescaria.fishing')),
            ],
            options={
                'verbose_name': 'Weight Ranking',
                'verbose_name_plural': 'Weight Ranking',
                'ordering': ['-fish_weight'],
            },
        ),
        migrations.CreateModel(
            name='RankingAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_species', models.CharField(max_length=30, verbose_name='Espécie do peixe')),
                ('fish_amount', models.IntegerField(verbose_name='Quantidade pescada')),
                ('image', models.ImageField(upload_to='fish_images', verbose_name='Foto do peixe')),
                ('fisherman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pescaria.fishing')),
            ],
            options={
                'verbose_name': 'Amount Ranking',
                'verbose_name_plural': 'Amount Ranking',
                'ordering': ['-fish_amount'],
            },
        ),
    ]
