# Generated by Django 3.1.2 on 2020-11-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pescado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingweight',
            name='fish_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Tamanho do peixe em cm'),
        ),
    ]
