# Generated by Django 3.1.2 on 2020-11-01 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('pescado', '0002_rankingweight_fish_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingamount',
            name='fisherman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.user'),
        ),
        migrations.AlterField(
            model_name='rankingweight',
            name='fisherman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.user'),
        ),
    ]
