# Generated by Django 3.1.2 on 2020-11-01 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('pescaria', '0002_auto_20201101_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishing',
            name='fisherman_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Capitão', to='usuario.user', verbose_name='Capitão'),
        ),
        migrations.AlterField(
            model_name='fishing',
            name='friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Amigo', to='usuario.user', verbose_name='Amigo'),
        ),
        migrations.AlterField(
            model_name='fishing',
            name='immediate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Imediato', to='usuario.user', verbose_name='Imediato'),
        ),
        migrations.AlterField(
            model_name='fishing',
            name='pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Piloto', to='usuario.user', verbose_name='Piloto'),
        ),
    ]
